#!/usr/bin/env python

import os
import argparse
import datetime

parser = argparse.ArgumentParser(description='option')
parser.add_argument('-n', dest='Name')
parser.add_argument('-l', dest='RunList')
parser.add_argument('-y', dest='Year')
parser.add_argument('--nmax', dest='NMax', default=0, type=int)

args = parser.parse_args()

runlist = open(args.RunList).readlines()
NJobs = len(runlist)

pwd = os.getcwd()
CMSSW_BASE = os.environ['CMSSW_BASE']
SCRAM_ARCH = os.environ['SCRAM_ARCH']
SKFlatWD = os.environ['SKFlatWD']
SKFlatTag = os.environ['SKFlatTag']

cfgfile = SKFlatWD+'/SKFlatMaker/script/TAMSA/RunSKFlatMaker_JECSQLite.py'

JobStartTime = datetime.datetime.now()
timestamp =  JobStartTime.strftime('%Y_%m_%d_%H%M%S')

outbasedir = '/gv0/DATA/SKFlat/'+SKFlatTag+'/'+args.Year+'/PrivateMC/'+args.Name+'/'
os.system('mkdir -p '+outbasedir)

#### first write the executable

JobName = timestamp+'__'+args.Name
os.system('mkdir -p '+JobName)
executable_filename = 'SKFlatMaker_'+args.Year+'_'+args.Name+'.sh'
executable = open(pwd+'/'+JobName+'/'+executable_filename,'w')
print>>executable,'''#!/bin/bash
SECTION=`printf $1`
WORKDIR=`pwd`

#### Don't make root history
export ROOT_HIST=0

#### use cvmfs for root ####
export CMS_PATH=/cvmfs/cms.cern.ch
source $CMS_PATH/cmsset_default.sh
export SCRAM_ARCH={0}
cd {1}/src/
echo "@@@@ SCRAM_ARCH = "$SCRAM_ARCH
echo "@@@@ cmsswrel = "$cmsswrel
echo "@@@@ scram..."
eval `scramv1 runtime -sh`
cd -
source {2}/run_${{SECTION}}.sh
'''.format(SCRAM_ARCH,CMSSW_BASE,pwd+'/'+JobName)
executable.close()

#### Write jds

concurrency_limits='concurrency_limits = n'+str(args.NMax)+'.'+os.getenv("USER")
jdsfile = open(pwd+'/'+JobName+'/submit.jds','w')
print>>jdsfile,'''executable = {1}
universe   = vanilla
arguments  = $(Process)
log = condor.log
getenv     = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
output = job_$(Process).log
error = job_$(Process).err
{2}
queue {0}
'''.format(str(NJobs), executable_filename,concurrency_limits)
jdsfile.close()

#### write job sh file

for i in range(0,NJobs):

  mass = runlist[i].strip('\n')

  filelist = open('filelist/'+args.Year+'/'+mass+'.txt').readlines()

  runfile = open(pwd+'/'+JobName+'/run_'+str(i)+'.sh','w')

  outdest = outbasedir+mass+'/'+timestamp+'/'
  os.system('mkdir -p '+outdest)

  infilelist = ""
  for f in filelist:
    if "#" in f:
      continue
    infilelist += 'file:'+f.strip('\n')+','
  infilelist = infilelist[:-1]

  cmd  = "cmsRun "+cfgfile+" "+"\\\n"
  cmd += "inputFiles="+infilelist+" \\\n"
  cmd += "outputFile="+outdest+"SKFlatNtuple_"+args.Year+"_MC_1.root"+" \\\n"
  cmd += "sampletype=PrivateMC year="+args.Year+" ScaleIDRange=1001,1045 PDFErrorIDRange=1046,1146 PDFAlphaSIDRange=1147,1148 PDFAlphaSScaleValue=0.75,0.75"

  runfile.write(cmd)

  runfile.close()















